version: '3.8'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=yii2basic
      - DB_USER=root
      - DB_PASSWORD=root

  db:
    image: mariadb:11
    container_name: yii2-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
